title: "üßû‚Äç‚ôÇÔ∏è XRP Genie Documentation"
description: "CLI tool and SDK for rapidly scaffolding XRPL wallet applications"
url: "https://zhaben.github.io"
baseurl: "/xrp-genie"

# Theme
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation
header_pages:
  - setup/web3auth-dashboard.md
  - setup/xaman-dashboard.md
  - guides/network-selection.md

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  setup:
    output: true
    permalink: /:collection/:name/
  guides:
    output: true
    permalink: /:collection/:name/
  help:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"